const LOGIN_USER_REQUEST_SAGA = 'LOGIN_USER_REQUEST_SAGA';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
const SIGNUP_USER_REQUEST_SAGA = 'SIGNUP_USER_REQUEST_SAGA';
const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
const GET_USER_DATA_REQUEST_SAGA = 'GET_USER_DATA_REQUEST_SAGA';
const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
const LOGOUT = 'LOGOUT';
const CLIENT_SET = 'CLIENT_SET';
const CLIENT_UNSET = 'CLIENT_UNSET';

module.exports = {
  LOGIN_USER_REQUEST_SAGA,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  SIGNUP_USER_REQUEST_SAGA,
  SIGNUP_USER_SUCCESS,
  SIGNUP_USER_FAILURE,
  GET_USER_DATA_REQUEST_SAGA,
  GET_USER_DATA_SUCCESS,
  GET_USER_DATA_FAILURE,
  LOGOUT,
  CLIENT_SET,
  CLIENT_UNSET
};
